import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
const String fontPoppinsBold = 'poppins bold';
const String fontRobotoRegular = 'roboto regular';
const String fontInterSemibold = 'inter semibold';
const String fontInterMedium = 'inter medium';
const String fontInterBold = 'inter bold';
const String fontInterRegular = 'inter regular';
const String fontCircularXXTTTrialMedium = 'circularXXTTTrial medium';
const String fontCircularXXTTTrialRegular = 'circularXXTTTrial regular';